export function VisionSection() {
    return (
        <div id="vision" className="bg-examly-base border-b border-gray-100 shadow-sm relative z-10 w-full py-24">
            <div className="max-w-6xl mx-auto px-6 w-full">
                <div className="text-center mb-16">
                    <h2 className="text-4xl font-bold text-gray-800 mb-4">Learning Should Be Engaging, Not Exhausting</h2>
                    <p className="text-xl text-gray-500 font-medium max-w-2xl mx-auto">Discover the features that make our platform the best choice for modern classrooms.</p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 flex flex-col items-start hover:border-examly-accent transition-colors duration-300">
                        <div className="w-12 h-12 rounded-xl bg-teal-50 flex items-center justify-center text-examly-accent mb-6">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                            </svg>
                        </div>
                        <h3 className="text-xl font-bold text-gray-800 mb-3">AI Question Generation</h3>
                        <p className="text-gray-500 font-medium leading-relaxed">Instantly generate high-quality quizzes using our advanced AI, saving hours of manual work.</p>
                    </div>
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 flex flex-col items-start hover:border-examly-accent transition-colors duration-300">
                        <div className="w-12 h-12 rounded-xl bg-teal-50 flex items-center justify-center text-examly-accent mb-6">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                            </svg>
                        </div>
                        <h3 className="text-xl font-bold text-gray-800 mb-3">Real-Time Sessions</h3>
                        <p className="text-gray-500 font-medium leading-relaxed">Host live interactive exams where every student's progress is synced simultaneously.</p>
                    </div>
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 flex flex-col items-start hover:border-examly-accent transition-colors duration-300">
                        <div className="w-12 h-12 rounded-xl bg-teal-50 flex items-center justify-center text-examly-accent mb-6">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002-2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                            </svg>
                        </div>
                        <h3 className="text-xl font-bold text-gray-800 mb-3">Instant Analytics</h3>
                        <p className="text-gray-500 font-medium leading-relaxed">Gain actionable insights from automated grading and detailed performance reports.</p>
                    </div>
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 flex flex-col items-start hover:border-examly-accent transition-colors duration-300">
                        <div className="w-12 h-12 rounded-xl bg-teal-50 flex items-center justify-center text-examly-accent mb-6">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
                            </svg>
                        </div>
                        <h3 className="text-xl font-bold text-gray-800 mb-3">Explore & Practice</h3>
                        <p className="text-gray-500 font-medium leading-relaxed">Discover public exam rooms generated by other educators to study and practice.</p>
                    </div>
                </div>
            </div>
        </div>
    );
}
